// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeWFPtHm4ULEnzpUHvomAoLRlDvVpvXCQ',
    appId: '1:981372129994:web:634a223d5f61951f57da33',
    messagingSenderId: '981372129994',
    projectId: 'note119-a099a',
    authDomain: 'note119-a099a.firebaseapp.com',
    storageBucket: 'note119-a099a.appspot.com',
    measurementId: 'G-F30Q0Q1RX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5y-tprNbIhybroaREf_WGcnZPYSVrC-8',
    appId: '1:981372129994:android:9f43f83dcd8381ba57da33',
    messagingSenderId: '981372129994',
    projectId: 'note119-a099a',
    storageBucket: 'note119-a099a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClZ1-SMHIG8FRNm2gqcQVBkufGCK6EBJ0',
    appId: '1:981372129994:ios:410215dbde56c2fd57da33',
    messagingSenderId: '981372129994',
    projectId: 'note119-a099a',
    storageBucket: 'note119-a099a.appspot.com',
    iosBundleId: 'com.example.firebaseExp119',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClZ1-SMHIG8FRNm2gqcQVBkufGCK6EBJ0',
    appId: '1:981372129994:ios:cde57d77c7ab45eb57da33',
    messagingSenderId: '981372129994',
    projectId: 'note119-a099a',
    storageBucket: 'note119-a099a.appspot.com',
    iosBundleId: 'com.example.firebaseExp119.RunnerTests',
  );
}
